# Generated by Django 4.2.19 on 2025-02-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=200, unique=True)),
                ('msisdn', models.CharField(max_length=10, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('user_role', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('socials', models.CharField(max_length=200)),
                ('category_of_interest', models.CharField(max_length=50)),
                ('job_notifications', models.CharField(max_length=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
