# Generated by Django 4.2.19 on 2025-12-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('application_id', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=200)),
                ('employer_id', models.CharField(max_length=200)),
                ('job_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(default='1', max_length=2)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(max_length=200, unique=True)),
                ('employer_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('contract_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=500)),
                ('education_level', models.CharField(max_length=200)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('required_skills', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('no_of_vacancies', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('record_status', models.CharField(default='1', max_length=2)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saved_job_id', models.CharField(max_length=200, unique=True)),
                ('employer_id', models.CharField(max_length=200)),
                ('user_id', models.CharField(max_length=200)),
                ('job_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_status', models.CharField(default='1', max_length=2)),
            ],
            options={
                'db_table': 'saved_jobs',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default=None, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='industry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='record_status',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='users',
            name='resume_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='category_of_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='job_notifications',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='msisdn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='socials',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
