# Generated by Django 4.2.19 on 2025-12-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_applications_jobs_savedjobs_users_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='description',
            field=models.TextField(),
        ),
    ]
